;;;; hyde.import.scm - GENERATED BY CHICKEN 4.13.0 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         regex
         irregex
         files
         data-structures
         extras
         srfi-1
         ports
         srfi-13
         utils
         posix
         sxml-transforms
         doctype
         matchable
         scss
         spiffy
         srfi-18
         colorize
         intarweb
         uri-common
         svnwiki-sxml
         defstruct
         sxpath
         html-parser
         hyde-page-eval-env
         (except hyde-page-eval-env current-page-eval-env)))
(##sys#register-compiled-module
  'hyde
  (list)
  '((load-hyde-file . hyde#load-hyde-file)
    (hyde-environment . hyde#hyde-environment)
    (hyde-environments . hyde#hyde-environments)
    (initialize-site . hyde#initialize-site)
    (generate-page . hyde#generate-page)
    (pathify . hyde#pathify)
    (make-external-translator . hyde#make-external-translator)
    (serve . hyde#serve)
    (source-dir . hyde#source-dir)
    (output-dir . hyde#output-dir)
    (layouts-dir . hyde#layouts-dir)
    (default-layouts . hyde#default-layouts)
    (clean-before-build . hyde#clean-before-build)
    (excluded-paths . hyde#excluded-paths)
    (default-extension . hyde#default-extension)
    (default-page-vars . hyde#default-page-vars)
    (page-eval-env . hyde#page-eval-env)
    (translators . hyde#translators)
    (compile-pages . hyde#compile-pages)
    (uri-path-prefix . hyde#uri-path-prefix)
    (markdown-program . hyde#markdown-program)
    (link-shortcuts . hyde#link-shortcuts)
    (sxml-conversion-rules . hyde#sxml-conversion-rules)
    (ignore-page? . hyde#ignore-page?)
    (around-page-translate . hyde#around-page-translate)
    (page-serve-handler . hyde#page-serve-handler)
    (pages . hyde#pages)
    (page-by-path . hyde#page-by-path)
    (read-page . hyde#read-page)
    (serve-page . hyde#serve-page)
    (current-page . hyde#current-page)
    (page? . hyde#page?)
    (page-source-path . hyde#page-source-path)
    (page-path . hyde#page-path)
    (page-vars . hyde#page-vars)
    (page-reader . hyde#page-reader)
    (page-writer . hyde#page-writer)
    (page-type . hyde#page-type)
    (translate-sxml . hyde#translate-sxml)
    (translate-scss . hyde#translate-scss)
    (translate-markdown . hyde#translate-markdown)
    (translate-svnwiki . hyde#translate-svnwiki)
    (environment-eval . hyde-page-eval-env#environment-eval)
    (environment-copy . hyde-page-eval-env#environment-copy)
    (environment-ref . hyde-page-eval-env#environment-ref)
    (environment-extend! . hyde-page-eval-env#environment-extend!)
    (environment-set! . hyde-page-eval-env#environment-set!)
    (make-page-eval-env . hyde-page-eval-env#make-page-eval-env))
  (list (cons 'define-hyde-environment
              (syntax-rules
                ()
                ((_ name e1 e2 ...)
                 (begin
                   (hyde-environments (cons 'name (hyde-environments)))
                   (when (eq? 'name (hyde-environment)) e1 e2 ...))))))
  (list))

;; END OF FILE
