;;;; hyde-atom.import.scm - GENERATED BY CHICKEN 4.13.0 -*- Scheme -*-

(eval '(import scheme chicken hyde atom rfc3339 posix extras srfi-1))
(##sys#register-compiled-module
  'hyde-atom
  (list)
  '((translate-atom . hyde-atom#translate-atom))
  (list)
  (list))

;; END OF FILE
